### ISSUE TITLE
Which task should be used to build Spike?

### ISSUE THREAD

**Issue by posttool** [marytts/gradle-marytts-voicebuilding-plugin#2]
I have downloaded https://github.com/psibre/dfki-spike-data as well as the flac file from Soundcloud. I have a few questions. 

* Does the TextGrid represent verified phone/time pairs? 
* Will this data be used for the build?
* What is the entry task for data that has been prepared this way?

**Comment by psibre** [comment]
> * Does the TextGrid represent verified phone/time pairs? 

Those are the timings that were used for the voice as released in the SEMAINE demonstrator -- they are force-aligned using EHMM. But the git repo allows us to nicely update and improve any glaring problems in a structured way.
> * Will this data be used for the build?

Yes.
> * What is the entry task for data that has been prepared this way?

This is still in progress. I'm not happy with the restrictions for auto-downloading from SoundCloud. Maybe one could register an app to connect with their API, but I'm in favor of a simple solution, because that allows us to use Gradle's dependency resolution engine (Ivy, actually) to retrieve the data with zero extra overhead.

**Comment by posttool** [comment]
Could you share a script that assumes the flac is already downloaded?

**Comment by psibre** [comment]
@posttool In case you'd like an update, there is now a [dedicated repo](https://github.com/marytts/voice-dfki-spike ) for voice-dfki-spike.
